import { getEnv } from '~/utils/getEnv'
import minimist from 'minimist'

const args = minimist(process.argv.slice(2))
const isDev = args.env === 'development'
export const isProduction = args.env === 'production'
const isTest = args.env === 'test'

const envConfig = () => ({
  APP_PORT: getEnv('PORT', '4000'),
  APP_HOST: getEnv('HOST', 'localhost'),
  BASE_PATH: getEnv('BASE_PATH', '/api'),

  MONGODB_URI: getEnv('MONGODB_URI'),
  DATABASE_NAME: getEnv('DATABASE_NAME'),
  DB_USERS_COLLECTION: getEnv('DB_USERS_COLLECTION'),
  DB_REFRESH_TOKEN_COLLECTION: getEnv('DB_REFRESH_TOKEN_COLLECTION'),
  DB_FOLLOWERS_COLLECTION: getEnv('DB_FOLLOWERS_COLLECTION'),
  DB_TWEETS_COLLECTION: getEnv('DB_TWEETS_COLLECTION'),
  DB_HASHTAGS_COLLECTION: getEnv('DB_HASHTAGS_COLLECTION'),

  ACCESS_TOKEN_SECRET_SIGNATURE: getEnv('ACCESS_TOKEN_SECRET_SIGNATURE'),
  REFRESH_TOKEN_SECRET_SIGNATURE: getEnv('REFRESH_TOKEN_SECRET_SIGNATURE'),
  ACCESS_TOKEN_LIFE: getEnv('ACCESS_TOKEN_LIFE'),
  REFRESH_TOKEN_LIFE: getEnv('REFRESH_TOKEN_LIFE'),
  EMAIL_VERIFY_TOKEN_SECRET_SIGNATURE: getEnv('EMAIL_VERIFY_TOKEN_SECRET_SIGNATURE'),
  EMAIL_VERIFY_TOKEN_LIFE: getEnv('EMAIL_VERIFY_TOKEN_LIFE'),
  FORGOT_PASSWORD_TOKEN_SECRET_SIGNATURE: getEnv('FORGOT_PASSWORD_TOKEN_SECRET_SIGNATURE'),
  FORGOT_PASSWORD_TOKEN_LIFE: getEnv('FORGOT_PASSWORD_TOKEN_LIFE'),

  GOOGLE_CLIENT_ID: getEnv('GOOGLE_CLIENT_ID'),
  GOOGLE_CLIENT_SECRET: getEnv('GOOGLE_CLIENT_SECRET'),
  GOOGLE_REDIRECT_URI: getEnv('GOOGLE_REDIRECT_URI'),
  CLIENT_REDIRECT_URI: getEnv('CLIENT_REDIRECT_URI')
})

export const environment = envConfig()
